theme: jekyll-theme-cayman
title: "Instagram Story Downloader by Micha Birklbauer"
description: "Project Website for Instagram Story Downloader"
show_downloads: "true"
github:
  zip_url: https://github.com/t0xic-m/instagram_story_downloader/archive/master.zip
  tar_url: https://github.com/t0xic-m/instagram_story_downloader/archive/master.tar.gz
