theme: jekyll-theme-minimal
title: "Instagram Story Downloader by Micha Birklbauer"
description: "Project Website for Instagram Story Downloader"
logo: https://raw.githubusercontent.com/t0xic-m/t0xic-m.github.io/master/avatar.jpg
show_downloads: "true"
github:
  zip_url: https://github.com/t0xic-m/instagram_story_downloader/archive/master.zip
  tar_url: https://github.com/t0xic-m/instagram_story_downloader/archive/master.tar.gz
